# Generated by Django 5.0.14 on 2026-08-14 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('DOCUMENT', 'Document unique'), ('DOCUMENTS', 'Plusieurs documents'), ('WORKSPACE', "Tout l'espace de travail")], default='WORKSPACE', max_length=20)),
                ('vulgarization_level', models.CharField(choices=[('SIMPLE', 'Simple'), ('INTERMEDIATE', 'Intermédiaire'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='conversations', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'user'), ('ASSISTANT', 'assistant')], max_length=10)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=30)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
